import { useEffect, useState } from "react";
import LoginContainer from "../../components/login/LoginContainer";
import LoginFormField from "../../components/login/LoginFormField";
import LoginButton from "../../components/login/LoginButton";
import { isEmail } from "../../helpers/utilities";
import Head from "next/head";

const initialFocus = {
  email: false,
};

const Recovery = () => {
  const [focus, setFocus] = useState(initialFocus);
  const [error, setError] = useState({});
  const [email, setEmail] = useState("");

  const handleError = (input, msg) => {
    setError({ ...error, [input]: msg });
  };

  const handleFocus = (e) => {
    let { name } = e.target;

    setFocus({ ...focus, [name]: true });
    handleError(name, null);
  };

  const handleBlur = (e) => {
    let { name, value } = e.target;

    setFocus({ ...focus, [name]: false });

    if (value === "") {
      handleError(name, "Required");
    } else if (name === "email" && !isEmail(value)) {
      handleError(name, "Invalid Format");
    } else {
      handleError(name, null);
    }
  };

  const handleChange = (e) => {
    let { name, value } = e.target;

    if (name === "email") {
      setEmail(value);
    } else if (name === "password") {
      setPassword(value);
    }

    if (value) {
      handleError(name, null);
    }
  };

  //Update state in autocomplete
  useEffect(() => {
    setEmail(document.getElementById("email").value);
  }, []);

  return (
    <>
      <Head>
        <title>RECOVERY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginContainer
        title="Recovery password"
        swap="Do you remember your password?"
        link="login"
      >
        <LoginFormField
          type="email"
          autoComplete="username"
          value={email}
          focus={focus.email}
          error={error.email}
          handleFocus={handleFocus}
          handleChange={handleChange}
          handleBlur={handleBlur}
        />
        <LoginButton disabled={!email}>Recover account</LoginButton>
      </LoginContainer>
    </>
  );
};

export default Recovery;
