import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LANDING PAGE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my{" "}
          <Link href="/">
            <a>App!</a>
          </Link>
        </h1>

        <nav className={styles.nav}>
          <Link href="/login">
            <a>Log in</a>
          </Link>
          <Link href="/signup">
            <a>Sign up</a>
          </Link>
          <Link href="/app">
            <a>App</a>
          </Link>
          <Link href="/app/settings">
            <a>App Settings</a>
          </Link>
        </nav>
      </main>
    </div>
  );
}
